---
development:
  cloud_name: livre-recettes
  api_key:  => ENV['CLOUDINARY_USERNAME'] 
  api_secret: => ENV['CLOUDINARY_PASSWORD'] 
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: livre-recettes
  api_key:  => ENV['CLOUDINARY_USERNAME'] 
  api_secret: => ENV['CLOUDINARY_PASSWORD'] 
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: livre-recettes
  api_key:  => ENV['CLOUDINARY_USERNAME'] 
  api_secret: => ENV['CLOUDINARY_PASSWORD'] 
  enhance_image_tag: true
  static_image_support: false
